import time
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
doc = SimpleDocTemplate("Oceaneering_Update.pdf",pagesize=letter,rightMargin=72,leftMargin=72,topMargin=72,bottomMargin=18)
Story=[]
logo = "logo.png"
signature = "signature.png"
magName = "Oceaneering"
issueNum = 12
subPrice = "99.00"
limitedDate = "03/05/2020"
freeGift = "tin foil hat"
formatted_time = time.ctime()
full_name = "Terje S Skauen"
address_parts = ["Vestre Svanholmen 56, Sandnes, Norway"]
im = Image(logo, 3*inch, 1.3*inch)
Story.append(im)
Story.append(Spacer(1, 42))
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='Justify', alignment=TA_JUSTIFY))
ptext = '<font size="10">%s</font>' % formatted_time
Story.append(Paragraph(ptext, styles["Normal"]))
Story.append(Spacer(1, 12))
# Create return address
ptext = '<font size="10">%s</font>' % full_name
Story.append(Paragraph(ptext, styles["Normal"]))       
for part in address_parts:
    ptext = '<font size="10">%s</font>' % part.strip()
    Story.append(Paragraph(ptext, styles["Normal"]))   
Story.append(Spacer(1, 42))
ptext = '<font size="10">Dear %s:</font>' % full_name.split()[0].strip()
Story.append(Paragraph(ptext, styles["Normal"]))
Story.append(Spacer(1, 12))
ptext = '<font size="10">Coronavirus (COVID-19) is a respiratory illness caused by a new virus.  Symptoms range from a mild cough to pneumonia. Some people recover easily, others may get very sick very quickly. There is evidence that it spreads from person to person. Good hygiene can prevent infection. Human to human transmission of coronaviruses is primarily thought to occur among close contacts via respiratory droplets generated by sneezing and coughing. </font>'
Story.append(Paragraph(ptext, styles["Justify"]))

Story.append(Spacer(1, 12))

ptext = '<font size="10">Oceaneering has developed a solid plan for fighting this epidemic. We are putting strong barriers in place to reduce the chances of transmission, and keeping our offshore locations operational.</font>'
Story.append(Paragraph(ptext, styles["Justify"]))

Story.append(Spacer(1, 42))
ptext = '<font size="10">Thank you very much and we look forward hearing from you.</font>'
Story.append(Paragraph(ptext, styles["Justify"]))
ptext = '<font size="10">Sincerely,</font>'
Story.append(Paragraph(ptext, styles["Normal"]))
Story.append(Spacer(1, 48))

sig = Image(signature, 3*inch, 0.5*inch)
Story.append(sig)
sig.hAlign = 'LEFT'

Story.append(Spacer(1, 3))

ptext = '<font size="12">Christopher Lyon</font>'
Story.append(Paragraph(ptext, styles["Normal"]))

Story.append(Spacer(1, 6))

ptext = '<font size="10">Technical Supervisor for Offshore Operations</font>'
Story.append(Paragraph(ptext, styles["Justify"]))

Story.append(Spacer(1, 12))
doc.build(Story)






""" 

otext = '<font size="12">We would like to welcome you to our subscriber base for %s Magazine! \
        You will receive %s issues at the excellent introductory price of $%s. Please respond by\
        %s to start receiving your subscription and get the following free gift: %s.</font>' % (magName, 
                                                                                                issueNum,
                                                                                                subPrice,
                                                                                                limitedDate,
                                                                                                freeGift) """